spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/weather
      username: weather
      password: weatherpassword
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
server:
   servlet:
      context-path: /api
   port: 10000
   ssl:
      key-store-type: PKCS12
      key-store: src\main\resources\leaseBogdan.p12
      key-store-password: leaseBogdan
      key-alias: leaseBogdan
      enabled: true
openweathermap:
   appkey: a4939368914f781731c890001e5d4f66
   url: http://api.openweathermap.org/data/2.5/weather